version: "{build}"

platform: x64

branches:
  only:
    - master

clone_depth: 10

skip_tags: true

environment:
  ATOM_CHANNEL: stable
  APM_TEST_PACKAGES:
  MOCHA_TIMEOUT: '5000'

install:
  - ps: Install-Product node 6

build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

test: off
deploy: off
