language: node_js
node_js: '6.9.4'
sudo: false
os: linux
dist: trusty

branches:
  only:
  - master

env:
  global:
    - ATOM_CHANNEL=stable
    - MOCHA_TIMEOUT=5000

notifications:
  email:
    on_success: never
    on_failure: always

install:
- npm install -g npm

script:
- ./scripts/cibuild
