module.exports =
  # This will work on JavaScript and CoffeeScript files, but not in js comments.
  selector: '.source.poe'
  disableForSelector: '.source.poe .comment'

  # This will take priority over the default provider, which has a priority of 0.
  # `excludeLowerPriority` will suppress any providers with a lower priority
  # i.e. The default provider will be suppressed
  inclusionPriority: 1
  excludeLowerPriority: true

  blocks:  [
    {
      snippet: '##############################\n##  ${1:        Heading       }  ##\n##############################\n$2'
      displayText: '## Heading ##'
    },
    { snippet: 'Show\n  ${1:Filter}\n  ${2:Action}' },
    { snippet: 'Hide\n  ${1:Filter}' }
  ]

  filters: [
    { snippet: 'BaseType ${1:type}' },
    { snippet: 'Class ${1:class}' },
    { snippet: 'Rarity ${1:[operator]} ${2:rarity}' },
    { snippet: 'ItemLevel ${1:[operator]} ${2:level}' },
    { snippet: 'DropLevel ${1:[operator]} ${2:level}' },
    { snippet: 'Quality ${1:[operator]} ${2:quality}' },
    { snippet: 'Sockets ${1:[operator]} ${2:sockets}' },
    { snippet: 'LinkedSockets ${1:[operator]} ${2:links}' },
    { snippet: 'Height ${1:[operator]} ${2:height}' },
    { snippet: 'Width ${1:[operator]} ${2:width}' },
    { snippet: 'SocketGroup ${1:group}' }
  ]

  actions: [
    { snippet: 'SetBackgroundColor ${1:red} ${2:green} ${3:blue} ${4:[alpha]}' },
    { snippet: 'SetBorderColor ${1:red} ${2:green} ${3:blue} ${4:[alpha]}' },
    { snippet: 'SetTextColor ${1:red} ${2:green} ${3:blue} ${4:[alpha]}' },
    { snippet: 'PlayAlertSound ${1:id} ${2:[volume]}' },
    { snippet: 'SetFontSize ${1:size}' }
  ]

  rarity: [
    { snippet: 'Normal' },
    { snippet: 'Magic' },
    { snippet: 'Rare' },
    { snippet: 'Unique' }
  ]

  operators: [
    { snippet: '>'},
    { snippet: '>='},
    { snippet: '='},
    { snippet: '<='},
    { snippet: '<'}
  ]

  classes: [
    { snippet: '"Life Flask"' },
    { snippet: '"Mana Flask"' },
    { snippet: '"Hybrid Flask"' },
    { snippet: 'Currency' },
    { snippet: 'Amulet' },
    { snippet: 'Ring' },
    { snippet: 'Claw' },
    { snippet: 'Dagger' },
    { snippet: 'Wand' },
    { snippet: '"One Hand Sword"' },
    { snippet: '"Thrusting One Hand Sword"' },
    { snippet: '"One Hand Axe"' },
    { snippet: '"One Hand Mace"' },
    { snippet: 'Bow' },
    { snippet: 'Staves' },
    { snippet: '"Two Hand Swords"' },
    { snippet: '"Two Hand Axes"' },
    { snippet: '"Two Hand Maces"' },
    { snippet: '"Active Skill Gems"' },
    { snippet: '"Support Skill Gems"' },
    { snippet: 'Quivers' },
    { snippet: 'Belt' },
    { snippet: 'Gloves' },
    { snippet: 'Boots' },
    { snippet: '"Body Armours"' },
    { snippet: 'Helmets' },
    { snippet: 'Shields' },
    { snippet: '"Stackable Currency"' },
    { snippet: '"Quest Items"' },
    { snippet: 'Sceptres' },
    { snippet: '"Utility Flasks"' },
    { snippet: 'Maps' },
    { snippet: '"Fishing Rods"' },
    { snippet: '"Map Fragments"' },
    { snippet: '"Hideout Doodads"' },
    { snippet: 'Microtransactions' },
    { snippet: 'Jewel' },
    { snippet: '"Divination Card"' },
    { snippet: 'Talisman' },#? Not sure
    { snippet: '"Labyrinth Item"' },
    { snippet: '"Labyrinth Trinket"' },
  ]

  quest: [
    { snippet: '"Alira\'s Amulet"' },
    { snippet: '"Allflame"' },
    { snippet: '"Ammonite Glyph"' },
    { snippet: '"Baleful Gem"' },
    { snippet: '"Bust of Gaius Sentari"' },
    { snippet: '"Bust of Hector Titucius"' },
    { snippet: '"Bust of Marceus Lioneye"' },
    { snippet: '"Chitus\' Plum"' },
    { snippet: '"Decanter Spiritus"' },
    { snippet: '"Deshret\'s Banner"' },
    { snippet: '"Golden Hand"' },
    { snippet: '"Golden Page"' },
    { snippet: '"Haliotis Glyph"' },
    { snippet: '"Infernal Talc"' },
    { snippet: '"Kraityn\'s Amulet"' },
    { snippet: '"Malachai\'s Entrails"' },
    { snippet: '"Malachai\'s Heart"' },
    { snippet: '"Malachai\'s Lungs"' },
    { snippet: '"Maligaro\'s Spike"' },
    { snippet: '"Medicine Chest"' },
    { snippet: '"Oak\'s Amulet"' },
    { snippet: '"Ribbon Spool"' },
    { snippet: '"Roseus Glyph"' },
    { snippet: '"Thaumetic Emblem"' },
    { snippet: '"The Eye of Desire"' },
    { snippet: '"The Eye of Fury"' },
    { snippet: '"Tolman\'s Bracelet"' },
    { snippet: '"Tower Key"' },
    #Labyrinth
    { snippet: '"Silver Key"' },
    { snippet: '"Golden Key"' },
    { snippet: '"Treasure Key"' },
    { snippet: '"Bane of the Loyal"' },
    { snippet: '"Cogs of Disruption"' },
    { snippet: '"Cube of Absorption"' },
    { snippet: '"Heart of the Gargoyle"' },
    { snippet: '"Orb of Elemental Essence"' },
    { snippet: '"Portal Shredder"' },
    { snippet: '"Rod of Detonation"' },
    { snippet: '"Sand of Eternity"' },
  ]

  amulets: [
    { snippet: '"Jet Amulet"' },
    { snippet: '"Paua Amulet"' },
    { snippet: '"Coral Amulet"' },
    { snippet: '"Lapis Amulet"' },
    { snippet: '"Jade Amulet"' },
    { snippet: '"Amber Amulet"' },
    { snippet: '"Gold Amulet"' },
    { snippet: '"Turquoise Amulet"' },
    { snippet: '"Agate Amulet"' },
    { snippet: '"Citrine Amulet"' },
    { snippet: '"Onyx Amulet"' },
  ]

  talisman: [
    #Tier 1
    { snippet: '"Ashscale Talisman"' },
    { snippet: '"Black Maw Talisman"' },
    { snippet: '"Bonespire Talisman"' },
    { snippet: '"Breakrib Talisman"' },
    { snippet: '"Chrysalis Talisman"' },
    { snippet: '"Deadhand Talisman"' },
    { snippet: '"Deep One Talisman"' },
    { snippet: '"Lone Antler Talisman"' },
    { snippet: '"Mandible Talisman"' },
    { snippet: '"Rot Head Talisman"' },
    { snippet: '"Undying Flesh Talisman"' },
    { snippet: '"Writhing Talisman"' },
    #Tier 2
    { snippet: '"Avian Twins Talisman"' },
    { snippet: '"Clutching Talisman"' },
    { snippet: '"Fangjaw Talisman"' },
    { snippet: '"Hexclaw Talisman"' },
    { snippet: '"Horned Talisman"' },
    { snippet: '"Primal Skull Talisman"' },
    { snippet: '"Splitnewt Talisman"' },
    { snippet: '"Wereclaw Talisman"' },
    #Tier 3
    { snippet: '"Longtooth Talisman"' },
    { snippet: '"Monkey Paw Talisman"' },
    { snippet: '"Monkey Twins Talisman"' },
    { snippet: '"Rotfeather Talisman"' },
    { snippet: '"Spinefuse Talisman"' },
    { snippet: '"Three Hands Talisman"' },
    { snippet: '"Three Rat Talisman"' },
    #Tier 4
    { snippet: '"Greatwold Talisman"' },
  ]

  belts: [
    { snippet: '"Chain Belt"' },
    { snippet: '"Rustic Sash"' },
    { snippet: '"Heavy Belt"' },
    { snippet: '"Leather Belt"' },
    { snippet: '"Golden Obi"' },
    { snippet: '"Cloth Belt"' },
    { snippet: '"Studded Belt"' },
  ]

  rings: [
    { snippet: '"Iron Ring"' },
    { snippet: '"Coral Ring"' },
    { snippet: '"Paua Ring"' },
    { snippet: '"Saphire Ring"' },
    { snippet: '"Topaz Ring"' },
    { snippet: '"Ruby Ring"' },
    { snippet: '"Gold Ring"' },
    { snippet: '"Golden Hoop"' },
    { snippet: '"Jet Ring"' },
    { snippet: '"Two-Stone Ring"' },
    { snippet: '"Moonstone Ring"' },
    { snippet: '"Diamond Ring"' },
    { snippet: '"Prismatic Ring"' },
    { snippet: '"Amethyst Ring"' },
    { snippet: '"Unset Ring"' },
  ]

  currency: [
    { snippet: '"Albino Rhoa Feather"' },
    { snippet: '"Alchemy Shard"' },
    { snippet: '"Alteration Shard"' },
    { snippet: '"Armourer\'s Scrap"' },
    { snippet: '"Blacksmith\'s Whetstone"' },
    { snippet: '"Blessed Orb"' },
    { snippet: '"Cartographer\s Chisel"' },
    { snippet: '"Chaos Orb"' },
    { snippet: '"Chromatic Orb"' },
    { snippet: '"Divine Orb"' },
    { snippet: '"Eternal Orb"' },
    { snippet: '"Exalted Orb"' },
    { snippet: '"Gemcutter\'s Prism"' },
    { snippet: '"Glassblower\'s Bauble"' },
    { snippet: '"Jeweller\'s Orb"' },
    { snippet: '"Mirror of Kalandra"' },
    { snippet: '"Orb of Alchemy"' },
    { snippet: '"Orb of Alteration"' },
    { snippet: '"Orb of Augmentation"' },
    { snippet: '"Orb of Chance"' },
    { snippet: '"Orb of Fusing"' },
    { snippet: '"Orb of Regret"' },
    { snippet: '"Orb of Scouring"' },
    { snippet: '"Orb of Transmutation"' },
    { snippet: '"Portal Scroll"' },
    { snippet: '"Regal Orb"' },
    { snippet: '"Scroll Fragment"' },
    { snippet: '"Scroll of Wisdom"' },
    { snippet: '"Transmutation Shard"' },
    { snippet: '"Vaal Orb"' }
    #Perandus
    { snippet: '"Perandus Coin"' },
    #Phrophecy
    { snippet: '"Silver Coin"' },
    { snippet: '"Prophecy"' },
  ]

  skills: [
    #strength/red Active
    { snippet: '"Abyssal Cry"' },
    { snippet: 'Anger' },
    { snippet: '"Ancestral Protector"' },
    { snippet: '"Ancestral Warchief"' },
    { snippet: '"Animate Guardian"' },
    { snippet: 'Cleave' },
    { snippet: '"Decoy Totem"' },
    { snippet: 'Determination' },
    { snippet: '"Devouring Totem"' },
    { snippet: '"Dominating Blow"' },
    { snippet: '"Earthquake"' },
    { snippet: '"Enduring Cry"' },
    { snippet: '"Flame Totem"' },
    { snippet: '"Glacial Hammer"' },
    { snippet: '"Ground Slam"' },
    { snippet: '"Heavy Strike"' },
    { snippet: '"Herald of Ash"' },
    { snippet: '"Ice Crash"' },
    { snippet: '"Immortal Call"' },
    { snippet: '"Infernal Blow"' },
    { snippet: '"Leap Slam"' },
    { snippet: '"Molten Shell"' },
    { snippet: 'Punishment' },
    { snippet: '"Purity of Fire"' },
    { snippet: '"Rallying Cry"' },
    { snippet: 'Reckoning' },
    { snippet: '"Rejuvenation Totem"' },
    { snippet: '"Searing Bond"' },
    { snippet: '"Shield Charge"' },
    { snippet: '"Shockwave Totem"' },
    { snippet: '"Static Strike"' },
    { snippet: '"Summon Flame Golem"' },
    { snippet: '"Summon Stone Golem"' },
    { snippet: '"Sunder"' },
    { snippet: 'Sweep' },
    { snippet: 'Vengeance' },
    { snippet: '"Vigilant Strike"' },
    { snippet: 'Vitality' },
    { snippet: '"Warlord\'s Mark"' },
    #strength/red support
    { snippet: '"Added Fire Damage Support"' },
    { snippet: '"Bloodlust Support"' },
    { snippet: '"Blood Magic Support"' },
    { snippet: '"Cast on melee Kill Support"' },
    { snippet: '"Cast when Damage Taken Support"' },
    { snippet: '"Cold to Fire Support"' },
    { snippet: '"Empower Support"' },
    { snippet: '"Endurance Charge on Melee Stun Support"' },
    { snippet: '"Fire Penetration Support"' },
    { snippet: '"Fortify Support"' },
    { snippet: '"Generosity Support"' },
    { snippet: '"Increased Burning Damage Support"' },
    { snippet: '"Increased Duration Support"' },
    { snippet: '"Iron Grip Support"' },
    { snippet: '"Iron Will Support"' },
    { snippet: '"Item Quantity Support"' },
    { snippet: '"Knockback Support"' },
    { snippet: '"Less Duration Support"' },
    { snippet: '"Life Gain on Hit Support"' },
    { snippet: '"Life Leech Support"' },
    { snippet: '"Melee Damage on Full Life Support"' },
    { snippet: '"Melee Physical Damage Support"' },
    { snippet: '"Melee Splash Support"' },
    { snippet: '"Multistrike Support"' },
    { snippet: '"Ranged Attack Totem Support"' },
    { snippet: '"Reduced Mana Support"' },
    { snippet: '"Spell Totem Support"' },
    { snippet: '"Stun Support"' },
    { snippet: '"Weapon Elemental Damage Support"' },
    #strength/red vaal
    { snippet: '"Vaal Glacial Hammer"' },
    { snippet: '"Vaal Ground Slam"' },
    { snippet: '"Vaal Immortal Call"' },
    { snippet: '"Vaal Lightning Strike"' },
    { snippet: '"Vaal Molten Shell"' },
    #dexterity/green active
    { snippet: '"Animate WEapon"' },
    { snippet: '"Arctic Armour"' },
    { snippet: 'Barrage' },
    { snippet: '"Bear Trap"' },
    { snippet: '"Bladefall"' },
    { snippet: '"Blade Vortex"' },
    { snippet: '"Blast Rain"' },
    { snippet: '"Blink Arrow"' },
    { snippet: '"Blood Rage"' },
    { snippet: '"Burning Arrow"' },
    { snippet: 'Cyclone' },
    { snippet: 'Desecrate' },
    { snippet: '"Detonate Dead"' },
    { snippet: '"Double Strike"' },
    { snippet: '"Dual Strike"' },
    { snippet: '"Elemental Hit"' },
    { snippet: '"Ethereal knives"' },
    { snippet: '"Explosive Arrow"' },
    { snippet: '"Fire Trap"' },
    { snippet: '"Flicker Strike"' },
    { snippet: '"Freeze Mine"' },
    { snippet: 'Frenzy' },
    { snippet: '"Frost Blades"' },
    { snippet: 'Grace' },
    { snippet: 'Haste' },
    { snippet: 'Hatred' },
    { snippet: '"Herald of Ice"' },
    { snippet: '"Ice Shot"' },
    { snippet: '"Ice Trap"' },
    { snippet: '"Lacerate"' },
    { snippet: '"Lightning Arrow"' },
    { snippet: '"Lightning Strike"' },
    { snippet: '"Mirror Arrow"' },
    { snippet: '"Phase Run"' },
    { snippet: '"Poacher\'s Mark"' },
    { snippet: '"Poison Arrow"' },
    { snippet: '"Projectile Weakness"' },
    { snippet: 'Puncture' },
    { snippet: '"Purity of Ice"' },
    { snippet: '"Rain of Arrows"' },
    { snippet: 'Reave' },
    { snippet: 'Riposte' },
    { snippet: '"Shrapnel Shot"' },
    { snippet: '"Siege Ballista"' },
    { snippet: '"Smoke Mine"' },
    { snippet: '"Spectral Throw"' },
    { snippet: '"Split Arrow"' },
    { snippet: '"Summon Ice Golem"' },
    { snippet: '"Temporal Chains"' },
    { snippet: '"Tornado Shot"' },
    { snippet: '"Viper Strike"' },
    { snippet: '"Whirling Blades"' },
    { snippet: '"Wild Strike"' },
    #dexterity/green support
    { snippet: '"Added Cold Damage Support"' },
    { snippet: '"Additional Accuracy Support"' },
    { snippet: '"Blind"' },
    { snippet: '"Block Chance Reduction Support"' },
    { snippet: '"Cast On Critical Strike Support"' },
    { snippet: '"Cast on Death Support"' },
    { snippet: '"Chain Support"' },
    { snippet: '"Chance to Flee Support"' },
    { snippet: '"Cluster Traps Support"' },
    { snippet: '"Cold Penetration Support"' },
    { snippet: '"Culling Strike Support"' },
    { snippet: '"Enhance Support"' },
    { snippet: '"Faster Attacks Support"' },
    { snippet: '"Faster Projectiles Support"' },
    { snippet: '"Fork Support"' },
    { snippet: '"Greater Multiple Projectiles Support"' },
    { snippet: '"Hypothermia Support"' },
    { snippet: '"Ice Bite Support"' },
    { snippet: '"Lesser Multiple Projectiles Support"' },
    { snippet: '"Mana Leech Support"' },
    { snippet: '"Multiple Traps Support"' },
    { snippet: '"Physical Projectile Attack Damage Support"' },
    { snippet: '"Pierce Support"' },
    { snippet: '"Point Blank Support"' },
    { snippet: '"Poison Support"' },
    { snippet: '"Rapid Decay Support"' },
    { snippet: '"Slower Projectiles Support"' },
    { snippet: '"Trap Support"' },
    { snippet: '"Trap and Mine Damage Support"' },
    { snippet: '"Trap Cooldown Support"' },
    { snippet: '"Void Manipulation Support"' },
    #dexterity/green vaal
    { snippet: '"Vaal Burning Arrow"' },
    { snippet: '"Vaal Cyclone"' },
    { snippet: '"Vaal Detonate Dead"' },
    { snippet: '"Vaal Double Strike"' },
    { snippet: '"Vaal Grace"' },
    { snippet: '"Vaal Haste"' },
    { snippet: '"Vaal Rain of Arrows"' },
    { snippet: '"Vall reave"' },
    { snippet: '"Vaal Spectral Throw"' },
    #intelligence/blue active
    { snippet: 'Arc' },
    { snippet: '"Arctiv Breath"' },
    { snippet: '"Assassin\'s Mark"' },
    { snippet: '"Ball Lightning"' },
    { snippet: '"Bone Offering"' },
    { snippet: 'Clarity' },
    { snippet: '"Cold Snap"' },
    { snippet: 'Conductivity' },
    { snippet: 'Contagion' },
    { snippet: '"Conversion Trap"' },
    { snippet: 'Convocation' },
    { snippet: 'Discharge' },
    { snippet: 'Discipline' },
    { snippet: '"Elemental Weakness"' },
    { snippet: 'Enfeeble' },
    { snippet: '"Essence Drain"' },
    { snippet: '"Fire Nova Mine"' },
    { snippet: 'Fireball' },
    { snippet: 'Firestorm' },
    { snippet: '"Flame Dash"' },
    { snippet: '"Flame Surge"' },
    { snippet: 'Flameblast' },
    { snippet: 'Flammability' },
    { snippet: '"Flesh Offering"' },
    { snippet: '"Freezing Pulse"' },
    { snippet: 'Frostbite' },
    { snippet: 'Frostbolt' },
    { snippet: '"Frost Bomb"' },
    { snippet: '"Frost Wall"' },
    { snippet: '"Glacial Cascade"' },
    { snippet: '"Herald of Thunder"' },
    { snippet: '"Ice Nova"' },
    { snippet: '"Ice Spear"' },
    { snippet: 'Incinerate' },
    { snippet: '"Kinetic Blast"' },
    { snippet: '"Lightning Tendrils"' },
    { snippet: '"Lightning Trap"' },
    { snippet: '"Lightning warp"' },
    { snippet: '"Magma Orb"' },
    { snippet: '"Orb of Storms"' },
    { snippet: '"Power Siphon"' },
    { snippet: '"Purity of Elements"' },
    { snippet: '"Purity of Lightning"' },
    { snippet: '"Raise Spectre"' },
    { snippet: '"Raise Zombie"' },
    { snippet: '"Righteous Fire"' },
    { snippet: '"Shock Nova"' },
    { snippet: 'Spark' },
    { snippet: '"Spirit Offering"' },
    { snippet: '"Storm Call"' },
    { snippet: '"Summon Chaos Golem"' },
    { snippet: '"Summon Raging Spirit"' },
    { snippet: '"Summon Skeletons"' },
    { snippet: '"Tempest Shield"' },
    { snippet: 'Vortex' },
    { snippet: 'Vulnerability' },
    { snippet: '"Wither"' },
    { snippet: 'Wrath' },
    #intelligence/blue support
    { snippet: '"Added Chaos Damage Support"' },
    { snippet: '"Added Lightning Damage Support"' },
    { snippet: '"Blasphemy Support"' },
    { snippet: '"Cast when Stunned Support"' },
    { snippet: '"Chance to Ignite Support"' },
    { snippet: '"Concentrated Effect Support"' },
    { snippet: '"Controlled Destruciton Support"' },
    { snippet: '"Curse on Hit Support"' },
    { snippet: '"Elemental Focus Support"' },
    { snippet: '"Elemental Proliferation Support"' },
    { snippet: '"Enlighten Support"' },
    { snippet: '"Faster Casting Support"' },
    { snippet: '"Increased Area of Effect Support"' },
    { snippet: '"Increased Critical Damage Support"' },
    { snippet: '"Increased Critical Strikes Support"' },
    { snippet: '"Innervate Support"' },
    { snippet: '"Item Rarity Support"' },
    { snippet: '"Lightning Penetration Support"' },
    { snippet: '"Minefield Support"' },
    { snippet: '"Minion and Totem Elemental Resistance Support"' },
    { snippet: '"Minion Damage Support"' },
    { snippet: '"Minion Life Support"' },
    { snippet: '"Minion Speed Support"' },
    { snippet: '"Physical to Lightning Support"' },
    { snippet: '"Power Charge On Critical Support"' },
    { snippet: '"Remote Mine Support"' },
    { snippet: '"Spell Echo Support"' },
    #Intelligence/blue vaal
    { snippet: '"Vaal Arc"' },
    { snippet: '"Vaal Clarity"' },
    { snippet: '"Vaal Cold Snap"' },
    { snippet: '"Vaal Discipline"' },
    { snippet: '"Vaal Fireball"' },
    { snippet: '"Vaal Flameblast"' },
    { snippet: '"Vaal Ice Nova"' },
    { snippet: '"Vaal Lightning Trap"' },
    { snippet: '"Vaal Lightning Warp"' },
    { snippet: '"Vaal Power Siphon"' },
    { snippet: '"Vaal Righteous Fire"' },
    { snippet: '"Vaal Spark"' },
    { snippet: '"Vaal Storm Call"' },
    { snippet: '"Vaal Summon Skeletons"' },
    #white gems
    { snippet: '"Detonate Mines"' },
    { snippet: 'Portal' }
  ]

  jewels: [
    { snippet: '"Cobalt Jewel"' },
    { snippet: '"Crimson Jewel"' },
    { snippet: '"Viridian Jewel"' },
  ]

  maps: [
    #Tier 1
    { snippet: '"Crypt Map"' },
    { snippet: '"Desert Map"' },
    { snippet: '"Dunes Map"' },
    { snippet: '"Dungeon Map"' },
    { snippet: '"Grotto Map"' },
    { snippet: '"Pit Map"' },
    { snippet: '"Tropical Island Map"' },
    #Tier 2
    { snippet: '"Arcade Map"' },
    { snippet: '"Cemetery Map"' },
    { snippet: '"Channel Map"' },
    { snippet: '"Mountain Ledge Map"' },
    { snippet: '"Sewer Map"' },
    { snippet: '"Thicket Map"' },
    { snippet: '"Wharf Map"' },
    #Tier 3
    { snippet: '"Ghetto Map"' },
    { snippet: '"Mud Geyser Map"' },
    { snippet: '"Museum Map"' },
    { snippet: '"Quarry Map"' },
    { snippet: '"Reef Map"' },
    { snippet: '"Spider Lair Map"' },
    { snippet: '"Vaal Pyramid Map"' },
    #Tier 4
    { snippet: '"Arena Map"' },
    { snippet: '"Overgrown Shrine Map"' },
    { snippet: '"Promenade Map"' },
    { snippet: '"Phantasmagoria Map"' },
    { snippet: '"Shore Map"' },
    { snippet: '"Spider Forest Map"' },
    { snippet: '"Tunnel Map"' },
    #Tier 5
    { snippet: '"Bog Map"' },
    { snippet: '"Coves Map"' },
    { snippet: '"Graveyard Map"' },
    { snippet: '"Pier Map"' },
    { snippet: '"Underground Sea Map"' },
    { snippet: '"Villa Map"' },
    #Tier 6
    { snippet: '"Arachnid Nest Map"' },
    { snippet: '"Catacomb Map"' },
    { snippet: '"Colonnade Map"' },
    { snippet: '"Dry Woods Map"' },
    { snippet: '"Strand Map"' },
    { snippet: '"Temple Map"' },
    #Tier 7
    { snippet: '"Jungle Valley Map"' },
    { snippet: '"Labyrinth Map"' },
    { snippet: '"Abandoned Cavern Map"' },
    { snippet: '"Torture Chamber Map"' },
    { snippet: '"Waste Pool Map"' },
    #Tier 8
    { snippet: '"Canyon Map"' },
    { snippet: '"Cells Map"' },
    { snippet: '"Dark Forest Map"' },
    { snippet: '"Dry Peninsula Map"' },
    { snippet: '"Orchard Map"' },
    #Tier 9
    { snippet: '"Arid Lake Map"' },
    { snippet: '"Gorge Map"' },
    { snippet: '"Malformation Map"' },
    { snippet: '"Residence Map"' },
    { snippet: '"Underground River Map"' },
    #Tier 10
    { snippet: '"Bazaar Map"' },
    { snippet: '"Chateau Map"' },
    { snippet: '"Necropolis Map"' },
    { snippet: '"Plateau Map"' },
    { snippet: '"Volcano Map"' },
    #Tier 11
    { snippet: '"Academy Map"' },
    { snippet: '"Crematorium Map"' },
    { snippet: '"Precinct Map"' },
    { snippet: '"Springs Map"' },
    #Tier 12
    { snippet: '"Arsenal Map"' },
    { snippet: '"Overgrown Ruin Map"' },
    { snippet: '"Shipyard Map"' },
    { snippet: '"Village Ruin Map"' },
    #Tier 13
    { snippet: '"Courtyard Map"' },
    { snippet: '"Excavation Map"' },
    { snippet: '"Wasteland Map"' },
    { snippet: '"Waterways Map"' },
    #Tier 14
    { snippet: '"Conservatory Map"' },
    { snippet: '"Palace Map"' },
    { snippet: '"Shrine Map"' },
    { snippet: '"Vaal Temple Map"' },
    { snippet: '"Plaza Map"' },
    #Tier 15
    { snippet: '"Abyss Map"' },
    { snippet: '"Colosseum Map"' },
    { snippet: '"Core Map"' }
    #Misc
    { snippet: '"The Apex of Sacrifice"' },
    { snippet: '"The Alluring Abyss"' },
    { snippet: '"Offering to the Goddess"' },
  ]

  fragments: [
    { snippet: '"Sacrifice at Dawn"' },
    { snippet: '"Sacrifice at Noon"' },
    { snippet: '"Sacrifice at Dusk"' },
    { snippet: '"Sacrifice at Midnight"' },
    { snippet: '"Mortal Grief"' },
    { snippet: '"Mortal Rage"' },
    { snippet: '"Mortal Hope"' },
    { snippet: '"Mortal Ignorance"' },
    #Prophecy
    { snippet: '"Eber\'s Key"' },
    { snippet: '"Yriel\'s Key"' },
    { snippet: '"Inya\'s Key"' },
    { snippet: '"Volkuur\'s Key"' },
  ]

  flasks: [
    #Life flasks
    { snippet: '"Small Life Flask"' },
    { snippet: '"Medium Life Flask"' },
    { snippet: '"Large Life Flask"' },
    { snippet: '"Greater Life Flask"' },
    { snippet: '"Grand Life Flask"' },
    { snippet: '"Giant Life Flask"' },
    { snippet: '"Colossal Life Flask"' },
    { snippet: '"Sacred Life Flask"' },
    { snippet: '"Hallowed Life Flask"' },
    { snippet: '"Sanctified Life Flask"' },
    { snippet: '"Divine Life Flask"' },
    { snippet: '"Eternal Life Flask"' },
    #Mana flasks
    { snippet: '"Small Mana Flask"' },
    { snippet: '"Medium Mana Flask"' },
    { snippet: '"Large Mana Flask"' },
    { snippet: '"Greater Mana Flask"' },
    { snippet: '"Grand Mana Flask"' },
    { snippet: '"Giant Mana Flask"' },
    { snippet: '"Colossal Mana Flask"' },
    { snippet: '"Sacred Mana Flask"' },
    { snippet: '"Hallowed Mana Flask"' },
    { snippet: '"Sanctified Mana Flask"' },
    { snippet: '"Divine Mana Flask"' },
    { snippet: '"Eternal Mana Flask"' },
    #Hybrid flasks
    { snippet: '"Small Hydbrid Flask"' },
    { snippet: '"Medium Hydbrid Flask"' },
    { snippet: '"Large Hybrid Flask"' },
    { snippet: '"Colossal Hydbrid Flask"' },
    { snippet: '"Sacred Hydbrid Flask"' },
    { snippet: '"Hallowed Hydbrid Flask"' },
    #Utility flasks
    { snippet: '"Quicksilver Flask"' },
    { snippet: '"Ruby Flask"' },
    { snippet: '"Sapphire Flask"' },
    { snippet: '"Topaz Flask"' },
    { snippet: '"Amethyst Flask"' },
    { snippet: '"Granity Flask"' },
    { snippet: '"Diamond Flask"' },
    { snippet: '"Jade Flask"' },
    { snippet: '"Quartz Flask"' }
    { snippet: '"Basalt Flask"' },
    { snippet: '"Aquamarine Flask"' },
    { snippet: '"Stibnite Flask"' },
    { snippet: '"Sulphur Flask"' },
    { snippet: '"Silver Flask"' },
    { snippet: '"Bismuth Flask"' },
  ]

  bows: [
    { snippet: '"Crude Bow"' },
    { snippet: '"Short Bow"' },
    { snippet: '"Long Bow"' },
    { snippet: '"Composite Bow"' },
    { snippet: '"Recurve Bow"' },
    { snippet: '"Bone Bow"' },
    { snippet: '"Royal Bow"' },
    { snippet: '"Death Bow"' },
    { snippet: '"Grove Bow"' },
    { snippet: '"Reflex Bow"' },
    { snippet: '"Decurve Bow"' },
    { snippet: '"Compound Bow"' },
    { snippet: '"Sniper Bow"' },
    { snippet: '"Ivory Bow"' },
    { snippet: '"Highborn Bow"' },
    { snippet: '"Decimation Bow"' },
    { snippet: '"Thicket Bow"' },
    { snippet: '"Steelwood Bow"' },
    { snippet: '"Citadel Bow"' },
    { snippet: '"Ranger Bow"' },
    { snippet: '"Assassin Bow"' },
    { snippet: '"Spine Bow"' },
    { snippet: '"Imperial Bow"' },
    { snippet: '"Harbinger Bow"' },
    { snippet: '"Maraketh Bow"' }
  ]

  claws: [
    { snippet: '"Nailed Fist"' },
    { snippet: '"Sharktooth Claw"' },
    { snippet: 'Awl' },
    { snippet: '"Cat\'s Paw"' },
    { snippet: 'Blinder' },
    { snippet: '"Timeworn Claw"' },
    { snippet: '"Sparkling Claw"' },
    { snippet: '"Fright Claw"' },
    { snippet: '"Double Claw"' },
    { snippet: '"Thresher Claw"' },
    { snippet: 'Gouger' },
    { snippet: '"Tiger\'s Paw"' },
    { snippet: '"Gut Ripper"' },
    { snippet: '"Prehistoric Claw"' },
    { snippet: '"Noble Claw"' },
    { snippet: '"Eagle Claw"' },
    { snippet: '"Twin Claw"' },
    { snippet: '"Great White Claw"' },
    { snippet: '"Throat Stabber"' },
    { snippet: '"Hellion\'s Paw"' },
    { snippet: '"Eye Gouger"' },
    { snippet: '"Vaal Claw"' },
    { snippet: '"Imperial Claw"' },
    { snippet: '"Terror Claw"' },
    { snippet: '"Gemini Claw"' },
  ]

  daggers: [
    { snippet: '"Glass Shank"' },
    { snippet: '"Skinning Knife"' },
    { snippet: '"Carving Knife"' },
    { snippet: 'Stiletto' },
    { snippet: '"Boot Knife"' },
    { snippet: '"Copper Kris"' },
    { snippet: 'Skean' },
    { snippet: '"Imp Dagger"' },
    { snippet: '"Flaying Knife"' },
    { snippet: '"Prong Dagger"' },
    { snippet: '"Butcher Knife"' },
    { snippet: 'Poignard' },
    { snippet: '"Boot Blade"' },
    { snippet: '"Golden Kris"' },
    { snippet: '"Royal Skean"' },
    { snippet: '"Fiend Dagger"' },
    { snippet: 'Trisula' },
    { snippet: '"Gutting Knife"' },
    { snippet: '"Slaughter Knife"' },
    { snippet: 'Ambusher' },
    { snippet: '"Ezomyte Dagger"' },
    { snippet: '"Platinum Kris"' },
    { snippet: '"Imperial Skean"' },
    { snippet: '"Demon Dagger"' },
    { snippet: 'Sai' }
  ]

  oneHandAxe: [
    { snippet: '"Rusted Hatchet"' },
    { snippet: '"Jade Hatchet"' },
    { snippet: '"Boarding Axe"' },
    { snippet: 'Cleaver' },
    { snippet: '"Broad Axe"' },
    { snippet: '"Arming Axe"' },
    { snippet: '"Decorative Axe"' },
    { snippet: '"Spectral Axe"' },
    { snippet: '"Etched Hatchet"' },
    { snippet: '"Jasper Axe"' },
    { snippet: 'Tomahawk' },
    { snippet: '"Wrist Chopper"' },
    { snippet: '"War Axe"' },
    { snippet: '"Chest Splitter"' },
    { snippet: '"Ceremonial Axe"' },
    { snippet: '"Wraith Axe"' },
    { snippet: '"Engraved Hatchet"' },
    { snippet: '"Karui Axe"' },
    { snippet: '"Siege Axe"' },
    { snippet: '"Reaver Axe"' },
    { snippet: '"Butcher Axe"' },
    { snippet: '"Vaal Hatchet"' },
    { snippet: '"Royal Axe"' },
    { snippet: '"Infernal Axe"' },
    { snippet: '"Runic Hatchet"' }
  ]

  oneHandMace: [
    { snippet: '"Driftwood Club"' },
    { snippet: '"Tribal Club"' },
    { snippet: '"Spiked Club"' },
    { snippet: '"Stone Hammer"' },
    { snippet: '"War Hammer"' },
    { snippet: '"Bladed Mace"' },
    { snippet: '"Ceremonial Mace"' },
    { snippet: '"Dream Mace"' },
    { snippet: '"Wyrm Mace"' },
    { snippet: '"Petrified Club"' },
    { snippet: '"Barbed Club"' },
    { snippet: '"Rock Breaker"' },
    { snippet: '"Battle Hammer"' },
    { snippet: '"Flanged Mace"' },
    { snippet: '"Ornate Mace"' },
    { snippet: '"Phantom Mace"' },
    { snippet: '"Dragon Mace"' },
    { snippet: '"Ancestral Club"' },
    { snippet: 'Tenderizer' },
    { snippet: 'Gavel' },
    { snippet: '"Legion Hammer"' },
    { snippet: 'Pernarch' },
    { snippet: '"Auric Mace"' },
    { snippet: '"Nightmare Mace"' },
    { snippet: '"Behemoth Mace"' }
  ]

  oneHandSword: [
    { snippet: '"Rusted Sword"' },
    { snippet: '"Copper Sword"' },
    { snippet: 'Sabre' },
    { snippet: '"Broad Sword"' },
    { snippet: '"War Sword"' },
    { snippet: '"Ancient Sword"' },
    { snippet: '"Elegant Sword"' },
    { snippet: '"Dusk Blade"' },
    { snippet: '"Hook Sword"' },
    { snippet: '"Variscite Blade"' },
    { snippet: 'Cutlass' },
    { snippet: 'Baselard' },
    { snippet: '"Battle Sword"' },
    { snippet: '"Elder Sword"' },
    { snippet: '"Graceful Sword"' },
    { snippet: '"Twilight Blade"' },
    { snippet: 'Grappler' },
    { snippet: '"Gemstone Sword"' },
    { snippet: '"Corsair Sword"' },
    { snippet: 'Gladius' },
    { snippet: '"Legion Sword"' },
    { snippet: '"Vaal Blade"' },
    { snippet: '"Eternal Sword"' },
    { snippet: '"Midnight Blade"' },
    { snippet: '"Tiger Hook"' }
  ]

  thrustingOneHandSword: [
    { snippet: '"Rusted Spike"' },
    { snippet: '"Whalebone Rapier"' },
    { snippet: '"Battered Foil"' },
    { snippet: '"Basket Rapier"' },
    { snippet: '"Jagged Foil"' },
    { snippet: '"Antique Rapier"' },
    { snippet: '"Elegant Foil"' },
    { snippet: '"Thorn Rapier"' },
    { snippet: 'Smallsword' },
    { snippet: '"Wyrmbone Rapier"' },
    { snippet: '"Burnished Foil"' },
    { snippet: 'Estoc' },
    { snippet: '"Serrated Foil"' },
    { snippet: '"Primeval Rapier"' },
    { snippet: '"Fancy Foil"' },
    { snippet: '"Apex Rapier"' },
    { snippet: '"Courtesan Sword"' },
    { snippet: '"Dragonbone Rapier"' },
    { snippet: '"Tempered Foil"' },
    { snippet: 'Pecoraro' },
    { snippet: '"Spiraled Foil"' },
    { snippet: '"Vaal Rapier"' },
    { snippet: '"Jewelled Foil"' },
    { snippet: '"Harpy Rapier"' },
    { snippet: '"Dragoon Sword"' }
  ]

  sceptre: [
    { snippet: '"Driftwood Sceptre"' },
    { snippet: '"Darkwood Sceptre"' },
    { snippet: '"Bronze Sceptre"' },
    { snippet: '"Quartz Sceptre"' },
    { snippet: '"Iron Sceptre"' },
    { snippet: '"Ochre Sceptre"' },
    { snippet: '"Ritual Sceptre"' },
    { snippet: '"Shadow Sceptre"' },
    { snippet: '"Grinning Fetish"' },
    { snippet: '"Horned Sceptre"' },
    { snippet: 'Sekhem' },
    { snippet: '"Crystal Sceptre"' },
    { snippet: '"Lead Sceptre"' },
    { snippet: '"Blood Sceptre"' },
    { snippet: '"Royal Sceptre"' },
    { snippet: '"Abyssal Sceptre"' },
    { snippet: '"Stag Sceptre"' },
    { snippet: '"Karui Sceptre"' },
    { snippet: '"Tyrant\'s Sekhem"' },
    { snippet: '"Opal Sceptre"' },
    { snippet: '"Platinum Sceptre"' },
    { snippet: '"Vaal Sceptre"' },
    { snippet: '"Carnal Sceptre"' },
    { snippet: '"Void Sceptre"' },
    { snippet: '"Sambar Sceptre"' }
  ]

  staff: [
    { snippet: '"Gnarled Branch"' },
    { snippet: '"Primitive Staff"' },
    { snippet: '"Long Staff"' },
    { snippet: '"Iron Staff"' },
    { snippet: '"Coiled Staff"' },
    { snippet: '"Royal Staff"' },
    { snippet: '"Vile Staff"' },
    { snippet: '"Crescent Staff"' },
    { snippet: '"Woodful Staff"' },
    { snippet: 'Quarterstaff' },
    { snippet: '"Military Staff"' },
    { snippet: '"Serpentine Staff"' },
    { snippet: '"Highborn Staff"' },
    { snippet: '"Foul Staff"' },
    { snippet: '"Moon Staff"' },
    { snippet: '"Primordial Staff"' },
    { snippet: 'Lathi' },
    { snippet: '"Ezomyte Staff"' },
    { snippet: '"Maelström Staff"' },
    { snippet: '"Imperial Staff"' },
    { snippet: '"Judgement Staff"' },
    { snippet: '"Eclipse Staff"' }
  ]

  twoHandAxe: [
    { snippet: '"Stone Axe"' },
    { snippet: '"Jade Chopper"' },
    { snippet: 'Woodsplitter' },
    { snippet: 'Poleaxe' },
    { snippet: '"Double Axe"' },
    { snippet: '"Gilded Axe"' },
    { snippet: '"Shadow Axe"' },
    { snippet: '"Dagger Axe"' },
    { snippet: '"Jasper Chopper"' },
    { snippet: '"Timber Axe"' },
    { snippet: '"Headsman Axe"' },
    { snippet: 'Labrys' },
    { snippet: '"Noble Axe"' },
    { snippet: '"Abyssal Axe"' },
    { snippet: '"Karui Chopper"' },
    { snippet: '"Talon Axe"' },
    { snippet: '"Sundering Axe"' },
    { snippet: '"Ezomyte Axe"' },
    { snippet: '"Vaal Axe"' },
    { snippet: '"Despot Axe"' },
    { snippet: '"Void Axe"' },
    { snippet: 'Fleshripper' }
  ]

  twoHandMace: [
    { snippet: '"Driftwood Maul"' },
    { snippet: '"Tribal Maul"' },
    { snippet: 'Mallet' },
    { snippet: 'Sledgehammer' },
    { snippet: '"Jagged Maul"' },
    { snippet: '"Brass Maul"' },
    { snippet: '"Fright Maul"' },
    { snippet: '"Morning Star"' },
    { snippet: '"Totemic Maul"' },
    { snippet: '"Great Mallet"' },
    { snippet: 'Steelhead' },
    { snippet: '"Spiny Maul"' },
    { snippet: '"Plated Maul"' },
    { snippet: '"Dread Maul"' },
    { snippet: '"Solar Maul"' },
    { snippet: '"Karui Maul"' },
    { snippet: '"Colossus Mallet"' },
    { snippet: 'Piledriver' },
    { snippet: 'Meatgrinder' },
    { snippet: '"Imperial Maul"' },
    { snippet: '"Terror Maul"' },
    { snippet: '"Coronal Maul"' }
  ]

  twoHandSword: [
    { snippet: '"Corroded Blade"' },
    { snippet: 'Longsword' },
    { snippet: '"Bastard Sword"' },
    { snippet: '"Two-Handed Sword"' },
    { snippet: '"Etched Greatsword"' },
    { snippet: '"Ornate Sword"' },
    { snippet: '"Spectral Sword"' },
    { snippet: '"Curved Blade"' },
    { snippet: '"Butcher Sword"' },
    { snippet: '"Footman Sword"' },
    { snippet: '"Highland Blade"' },
    { snippet: '"Engraved Greatsword"' },
    { snippet: '"Tiger Sword"' },
    { snippet: '"Wraith Sword"' },
    { snippet: '"Lithe Blade"' },
    { snippet: '"Headman\'s Sword"' },
    { snippet: '"Reaver Sword"' },
    { snippet: '"Ezomyte Blade"' },
    { snippet: '"Vaal Greatsword"' },
    { snippet: '"Lion Sword"' },
    { snippet: '"Infernal Sword"' },
    { snippet: '"Exquisite Blade"' }
  ]

  wand: [
    { snippet: '"Driftwood Wand"' },
    { snippet: '"Goat\'s Horn"' },
    { snippet: '"Carved Wand"' },
    { snippet: '"Quartz Wand"' },
    { snippet: '"Spiraled Wand"' },
    { snippet: '"Sage Wand"' },
    { snippet: '"Pagan Wand"' },
    { snippet: '"Faun\'s Horn"' },
    { snippet: '"Engraved Wand"' },
    { snippet: '"Crystal Wand"' },
    { snippet: '"Serpent Wand"' },
    { snippet: '"Omen Wand"' },
    { snippet: '"Heathen Wand"' },
    { snippet: '"Demon\'s Horn"' },
    { snippet: '"Imbued Wand"' },
    { snippet: '"Opal Wand"' },
    { snippet: '"Tornado Wand"' },
    { snippet: '"Prophecy Wand"' },
    { snippet: '"Profane Wand"' }
  ]

  bodyArmour: [
    { snippet: '"Plate Vest"' },
    { snippet: '"Shabby Jerkin"' },
    { snippet: '"Simple Robe"' },
    { snippet: '"Scale Vest"' },
    { snippet: '"Padded Vest"' },
    { snippet: '"Chainmail Vest"' },
    { snippet: 'Chestplate' },
    { snippet: '"Chainmail Tunic"' },
    { snippet: '"Light Brigandine"' },
    { snippet: '"Strapped Leather"' },
    { snippet: '"Oiled Vest"' },
    { snippet: '"Silken Vest"' },
    { snippet: '"Buckskin Tunic"' },
    { snippet: '"Copper Plate"' },
    { snippet: '"Ringmail Coat"' },
    { snippet: '"Scale Doublet"' },
    { snippet: '"Scholar\'s Robe"' },
    { snippet: '"Padded Jacket"' },
    { snippet: '"Chainmail Doublet"' },
    { snippet: '"War Plate"' },
    { snippet: '"Infantry Brigandine"' },
    { snippet: '"Oiled Coat"' },
    { snippet: '"Wild Leather"' },
    { snippet: '"Silken Garb"' },
    { snippet: '"Scarlet Raiment"' },
    { snippet: '"Full Ringmail"' },
    { snippet: '"Full Scale Armour"' },
    { snippet: '"Mage\'s Vestment"' },
    { snippet: '"Full Leather"' },
    { snippet: '"Full Plate"' },
    { snippet: '"Waxed Garb"' },
    { snippet: '"Soldier\'s Brigandine"' },
    { snippet: '"Silk Robe"' },
    { snippet: '"Arena Plate"' },
    { snippet: '"Full Chainmail"' },
    { snippet: '"Sun Leather"' },
    { snippet: '"Field Lamellar"' },
    { snippet: '"Cabalist Regalia"' },
    { snippet: '"Thief\'s Garb"' },
    { snippet: '"Holy Chainmail"' },
    { snippet: '"Bone Armour"' },
    { snippet: '"Lordly Plate"' },
    { snippet: '"Bronze Plate"' },
    { snippet: '"Eelskin Tunic"' },
    { snippet: '"Sage\'s Robe"' },
    { snippet: '"Wyrmscale Doublet"' },
    { snippet: '"Latticed Ringmail"' },
    { snippet: '"Quilted Jacket"' },
    { snippet: '"Frontier Leather"' },
    { snippet: '"Battle Plate"' },
    { snippet: '"Silken Wrap"' },
    { snippet: '"Hussar Brigandine"' },
    { snippet: '"Crusader Chainmail"' },
    { snippet: '"Sleek Coat"' },
    { snippet: '"Sun Plate"' },
    { snippet: '"Glorious Leather"' },
    { snippet: '"Conjurer\'s Vestment"' },
    { snippet: '"Full Wyrmscale"' },
    { snippet: '"Ornate Ringmail"' },
    { snippet: '"Crimson Raiment"' },
    { snippet: '"Coronal Leather"' },
    { snippet: '"Spidersilk Robe"' },
    { snippet: '"Colosseum Plate"' },
    { snippet: '"Commander\'s Brigandine"' },
    { snippet: '"Chain Hauberk"' },
    { snippet: '"Lacquered Garb"' },
    { snippet: '"Destroyer Regalia"' },
    { snippet: '"Majestic Plate"' },
    { snippet: '"Cutthroat\'s Garb"' },
    { snippet: '"Battle Lamellar"' },
    { snippet: '"Devout Chainmail"' },
    { snippet: '"Crypt Armour"' },
    { snippet: '"Golden Plate"' },
    { snippet: '"Savant\'s Robe"' },
    { snippet: '"Sharkskin Tunic"' },
    { snippet: '"Dragonscale Doublet"' },
    { snippet: '"Loricated Ringmail"' },
    { snippet: '"Destiny Leather"' },
    { snippet: '"Crusader Plate"' },
    { snippet: '"Necromancer Silks"' },
    { snippet: '"Sentinel Jacket"' },
    { snippet: '"Desert Brigandine"' },
    { snippet: '"Conquest Chainmail"' },
    { snippet: '"Exquisite Leather"' },
    { snippet: '"Varnished Coat"' },
    { snippet: '"Occultist\'s Vestment"' },
    { snippet: '"Astral Plate"' },
    { snippet: '"Full Dragonscale"' },
    { snippet: '"Elegant Ringmail"' },
    { snippet: '"Blood Raiment"' },
    { snippet: '"Widowsilk Robe"' },
    { snippet: '"Zodiac Leather"' },
    { snippet: '"Gladiator Plate"' },
    { snippet: '"General\'s Brigandine"' },
    { snippet: '"Saint\'s Hauberk"' },
    { snippet: '"Vaal Regalia"' },
    { snippet: '"Glorious Plate"' },
    { snippet: '"Assassin\'s Garb"' },
    { snippet: '"Sadist Garb"' },
    { snippet: '"Triumphant Lamellar"' },
    { snippet: '"Saintly Chainmail"' },
    { snippet: '"Carnal Armour"' },
    { snippet: '"Sacrificial Garb"' }
  ]

  boots: [
    { snippet: '"Iron Greaves"' },
    { snippet: '"Wool Shoes"' },
    { snippet: '"Rawhide Boots"' },
    { snippet: '"Chain Boots"' },
    { snippet: '"Wrapped Boots"' },
    { snippet: '"Leatherscale Boots"' },
    { snippet: '"Steel Greaves"' },
    { snippet: '"Velvet Slippers"' },
    { snippet: '"Goathide Boots"' },
    { snippet: '"Ringmail Boots"' },
    { snippet: '"Strapped Boots"' },
    { snippet: '"Ironscale Boots"' },
    { snippet: '"Deerskin Boots"' },
    { snippet: '"Silk Slippers"' },
    { snippet: '"Plated Greaves"' },
    { snippet: '"Clasped Boots"' },
    { snippet: '"Mesh Boots"' },
    { snippet: '"Bronzescale Boots"' },
    { snippet: '"Scholar Boots"' },
    { snippet: '"Reinforced Greaves"' },
    { snippet: '"Shackled Boots"' },
    { snippet: '"Nubuck Boots"' },
    { snippet: '"Steelscale Boots"' },
    { snippet: '"Riveted Boots"' },
    { snippet: '"Antique Greaves"' },
    { snippet: '"Satin Slippers"' },
    { snippet: '"Eelskin Boots"' },
    { snippet: '"Zealot Boots"' },
    { snippet: '"Trapper Boots"' },
    { snippet: '"Serpentscale Boots"' },
    { snippet: '"Sharkskin Boots"' },
    { snippet: '"Samite Slippers"' },
    { snippet: '"Ancient Greaves"' },
    { snippet: '"Ambush Boots"' },
    { snippet: '"Soldier Boots"' },
    { snippet: '"Wyrmscale Boots"' },
    { snippet: '"Conjurer Boots"' },
    { snippet: '"Goliath Greaves"' },
    { snippet: '"Shagreen Boots"' },
    { snippet: '"Carnal Boots"' },
    { snippet: '"Legion Boots"' },
    { snippet: '"Hydrascale Boots"' },
    { snippet: '"Arcanist Slippers"' },
    { snippet: '"Stealth Boots"' },
    { snippet: '"Vaal Greaves"' },
    { snippet: '"Assassin\'s Boots"' },
    { snippet: '"Crusader Boots"' },
    { snippet: '"Dragonscale Boots"' },
    { snippet: '"Sorcerer Boots"' },
    { snippet: '"Titan Greaves"' },
    { snippet: '"Murder Boots"' },
    { snippet: '"Slink Boots"' }
  ]

  gloves: [
    { snippet: '"Iron Gauntlets"' },
    { snippet: '"Rawhide Gloves"' },
    { snippet: '"Wool Gloves"' },
    { snippet: '"Fishscale Gauntlets"' },
    { snippet: '"Wrapped Mitts"' },
    { snippet: '"Chain Gloves"' },
    { snippet: '"Goathide Gloves"' },
    { snippet: '"Plated Gauntlets"' },
    { snippet: '"Velvet Gloves"' },
    { snippet: '"Golden Bracers"' },
    { snippet: '"Ironscale Gauntlets"' },
    { snippet: '"Strapped Mitts"' },
    { snippet: '"Ringmail Gloves"' },
    { snippet: '"Deerskin Gloves"' },
    { snippet: '"Bronze Gauntlets"' },
    { snippet: '"Silk Gloves"' },
    { snippet: '"Bronzescale Gauntlets"' },
    { snippet: '"Clasped Mitts"' },
    { snippet: '"Mesh Gloves"' },
    { snippet: '"Nubuck Gloves"' },
    { snippet: '"Steel Gauntlets"' },
    { snippet: '"Trapper Mitts"' },
    { snippet: '"Embroidered Gloves"' },
    { snippet: '"Steelscale Gauntlets"' },
    { snippet: '"Riveted Gloves"' },
    { snippet: '"Eelskin Gloves"' },
    { snippet: '"Antique Gauntlets"' },
    { snippet: '"Satin Gloves"' },
    { snippet: '"Zealot Gloves"' },
    { snippet: '"Serpentscale Gauntlets"' },
    { snippet: '"Sharkskin Gloves"' },
    { snippet: '"Ambush Mitts"' },
    { snippet: '"Samite Gloves"' },
    { snippet: '"Ancient Gauntlets"' },
    { snippet: '"Wyrmscale Gauntlets"' },
    { snippet: '"Carnal Mitts"' },
    { snippet: '"Soldier Gloves"' },
    { snippet: '"Goliath Gauntlets"' },
    { snippet: '"Shagreen Gloves"' },
    { snippet: '"Conjurer Gloves"' },
    { snippet: '"Legion Gloves"' },
    { snippet: '"Assassin\'s Mitts"' },
    { snippet: '"Hydrascale Gauntlets"' },
    { snippet: '"Arcanist Gloves"' },
    { snippet: '"Stealth Gloves"' },
    { snippet: '"Vaal Gauntlets"' },
    { snippet: '"Crusader Gloves"' },
    { snippet: '"Murder Mitts"' },
    { snippet: '"Dragonscale Gauntlets"' },
    { snippet: '"Sorcerer Gloves"' },
    { snippet: '"Titan Gauntlets"' },
    { snippet: '"Slink Gloves"' }
  ]

  helmets: [
    { snippet: '"Iron Hat"' },
    { snippet: '"Vine Circlet"' },
    { snippet: '"Leather Cap"' },
    { snippet: '"Battered Helm"' },
    { snippet: '"Scare Mask"' },
    { snippet: '"Rusted Coif"' },
    { snippet: '"Cone Helmet"' },
    { snippet: '"Iron Circlet"' },
    { snippet: 'Tricorne' },
    { snippet: '"Plague Mask"' },
    { snippet: '"Soldier Helmet"' },
    { snippet: 'Sallet' },
    { snippet: '"Torture Cage"' },
    { snippet: '"Iron Mask"' },
    { snippet: '"Barbute Helmet"' },
    { snippet: '"Leather Hood"' },
    { snippet: '"Great Helmet"' },
    { snippet: '"Visored Sallet"' },
    { snippet: '"Close Helmet"' },
    { snippet: '"Tribal Circlet"' },
    { snippet: '"Festival Mask"' },
    { snippet: '"Wolf Pelt"' },
    { snippet: '"Crusader Helmet"' },
    { snippet: '"Gilded Sallet"' },
    { snippet: '"Bone Circlet"' },
    { snippet: '"Golden Mask"' },
    { snippet: '"Gladiator Helmet"' },
    { snippet: '"Secutor Helm"' },
    { snippet: '"Aventail Helmet"' },
    { snippet: '"Raven Mask"' },
    { snippet: '"Lunaris Circlet"' },
    { snippet: '"Reaver Helmet"' },
    { snippet: '"Hunter Hood"' },
    { snippet: '"Fencer Helm"' },
    { snippet: '"Zealot Helmet"' },
    { snippet: '"Callous Mask"' },
    { snippet: '"Noble Tricorne"' },
    { snippet: '"Steel Circlet"' },
    { snippet: '"Siege Helmet"' },
    { snippet: '"Lacquered Helmet"' },
    { snippet: '"Regicide Mask"' },
    { snippet: '"Great Crown"' },
    { snippet: '"Necromancer Circlet"' },
    { snippet: '"Ursine Pelt"' },
    { snippet: '"Samite Helmet"' },
    { snippet: '"Harlequin Mask"' },
    { snippet: '"Fluted Bascinet"' },
    { snippet: '"Magistrate Crown"' },
    { snippet: '"Solaris Circlet"' },
    { snippet: '"Silken Hood"' },
    { snippet: '"Ezomyte Burgonet"' },
    { snippet: '"Vaal Mask"' },
    { snippet: '"Prophet Crown"' },
    { snippet: '"Pig-Faced Bascinet"' },
    { snippet: '"Sinner Tricorne"' },
    { snippet: '"Mind Cage"' },
    { snippet: '"Royal Burgonet"' },
    { snippet: '"Nightmare Bascinet"' },
    { snippet: '"Deicide Mask"' },
    { snippet: '"Praetor Crown"' },
    { snippet: '"Eternal Burgonet"' },
    { snippet: '"Hubris Circlet"' },
    { snippet: '"Lion Pelt"' }
  ]

  shields: [
    { snippet: '"Splintered Tower Shield"' },
    { snippet: '"Goathide Buckler"' },
    { snippet: '"Twig Spirit Shield"' },
    { snippet: '"Rotted Round Shield"' },
    { snippet: '"Spiked Bundle"' },
    { snippet: '"Corroded Tower Shield"' },
    { snippet: '"Plank Kite Shield"' },
    { snippet: '"Pine Buckler"' },
    { snippet: '"Yew Spirit Shield"' },
    { snippet: '"Rawhide Tower Shield"' },
    { snippet: '"Fir Round Shield"' },
    { snippet: '"Driftwood Spiked Shield"' },
    { snippet: '"Linden Kite Shield"' },
    { snippet: '"Bone Spirit Shield"' },
    { snippet: '"Painted Buckler"' },
    { snippet: '"Cedar Tower Shield"' },
    { snippet: '"Studded Round Shield"' },
    { snippet: '"Alloyed Spike Shield"' },
    { snippet: '"Reinforced Kite Shield"' },
    { snippet: '"Hammered Buckler"' },
    { snippet: '"Tarnished Spirit Shield"' },
    { snippet: '"Copper Tower Shield"' },
    { snippet: '"Layered Kite Shield"' },
    { snippet: '"Burnished Spike Shield"' },
    { snippet: '"Scarlet Round Shield"' },
    { snippet: '"Jingling Spirit Shield"' },
    { snippet: '"War Buckler"' },
    { snippet: '"Reinforced Tower Shield"' },
    { snippet: '"Ornate Spiked Shield"' },
    { snippet: '"Splendid Round Shield"' },
    { snippet: '"Brass Spirit Shield"' },
    { snippet: '"Ceremonial Kite Shield"' },
    { snippet: '"Gilded Buckler"' },
    { snippet: '"Painted Tower Shield"' },
    { snippet: '"Walnut Spirit Shield"' },
    { snippet: '"Oak Buckler"' },
    { snippet: '"Redwood Spiked Shield"' },
    { snippet: '"Maple Round Shield"' },
    { snippet: '"Buckskin Tower Shield"' },
    { snippet: '"Etched Kite Shield"' },
    { snippet: '"Ivory Spirit Shield"' },
    { snippet: '"Enameled Buckler"' },
    { snippet: '"Mahogany Tower Shield"' },
    { snippet: '"Compound Spiked Shield"' },
    { snippet: '"Spiked Round Shield"' },
    { snippet: '"Ancient Spirit Shield"' },
    { snippet: '"Corrugated Buckler"' },
    { snippet: '"Steel Kite Shield"' },
    { snippet: '"Bronze Tower Shield"' },
    { snippet: '"Crimson Round Shield"' },
    { snippet: '"Chiming Spirit Shield"' },
    { snippet: '"Polished Spiked Shield"' },
    { snippet: '"Laminated Kite Shield"' },
    { snippet: '"Battle Buckler"' },
    { snippet: '"Girded Tower Shield"' },
    { snippet: '"Thorium Spirit Shield"' },
    { snippet: '"Golden Buckler"' },
    { snippet: '"Sovereign Spiked Shield"' },
    { snippet: '"Baroque Round Shield"' },
    { snippet: '"Angelic Kite Shield"' },
    { snippet: '"Crested Tower Shield"' },
    { snippet: '"Lacewood Spirit Shield"' },
    { snippet: '"Ironwood Buckler"' },
    { snippet: '"Alder Spike Shield"' },
    { snippet: '"Shagreen Tower Shield"' },
    { snippet: '"Teak Round Shield"' },
    { snippet: '"Branded Kite Shield"' },
    { snippet: '"Fossilized Spirit Shield"' },
    { snippet: '"Lacquered Buckler"' },
    { snippet: '"Ebony Tower Shield"' },
    { snippet: '"Spiny Round Shield"' },
    { snippet: '"Ezomyte Spiked Shield"' },
    { snippet: '"Vaal Spirit Shield"' },
    { snippet: '"Champion Kite Shield"' },
    { snippet: '"Vaal Buckler"' },
    { snippet: '"Ezomyte Tower Shield"' },
    { snippet: '"Harmonic Spirit Shield"' },
    { snippet: '"Mosaic Kite Shield"' },
    { snippet: '"Mirrored Spiked Shield"' },
    { snippet: '"Crusader Buckler"' },
    { snippet: '"Cardinal Round Shield"' },
    { snippet: '"Colossal Tower Shield"' },
    { snippet: '"Archon Kite Shield"' },
    { snippet: '"Titanium Spirit Shield"' },
    { snippet: '"Imperial Buckler"' },
    { snippet: '"Elegant Round Shield"' },
    { snippet: '"Supreme Spiked Shield"' },
    { snippet: '"Pinnacle Tower Shield"' }
  ]

  excludedPrefixes: [
    #filters
    'Class',   'BaseType',      'ItemLevel',   'DropLevel', 'Quality', 'Rarity',
    'Sockets', 'LinkedSockets', 'SocketGroup', 'Height',    'Width',
    #actions
    'PlayAlertSound', 'SetBackgroundColor', 'SetBorderColor', 'SetFontSize', 'SetTextColor',
    #misc
    '[operator]'
  ]

  # Required: Return a promise, an array of suggestions, or null.
  getSuggestions: ({editor, bufferPosition, scopeDescriptor, prefix}) ->
    suggestions = []
    # The default prefix doesn't include the # symbol which is desired for headers.
    prefix = @getPrefix(editor, bufferPosition)

    if 'source.poe' == scopeDescriptor.scopes[scopeDescriptor.scopes.length - 1]
      suggestions = @blocks

    if 'show.block.poe' == scopeDescriptor.scopes[scopeDescriptor.scopes.length - 1]
      suggestions = @filters.concat @actions

    if 'hide.block.poe' == scopeDescriptor.scopes[scopeDescriptor.scopes.length - 1]
      suggestions = @filters

    if 'filter.rarity.poe' in scopeDescriptor.scopes and prefix not in @excludedPrefixes
      suggestions = @rarity

    if 'filter.class.poe' in scopeDescriptor.scopes and prefix not in @excludedPrefixes
      suggestions = @classes

    if 'filter.basetype.poe' in scopeDescriptor.scopes and prefix not in @excludedPrefixes
      suggestions = suggestions.concat(@quest, @amulets, @talisman, @belts, @rings, @currency, @skills, @jewels, @maps, @fragments, @flasks,
                                       @bows, @claws, @daggers, @oneHandAxe, @oneHandMace, @oneHandSword, @thrustingOneHandSword, @sceptre, @staff, @twoHandAxe, @twoHandMace, @twoHandSword, @wand,
                                       @bodyArmour, @boots, @gloves, @helmets, @shields)

    if /filter\..*\.operator/.test(scopeDescriptor.scopes[scopeDescriptor.scopes.length - 1]) or prefix == '[operator]'
      suggestions = @operators

    @setReplacementPrefix(prefix, suggestions)
    @orderSuggestions(prefix, suggestions)

    return suggestions

  getPrefix: (editor, bufferPosition) ->
    line = editor.getTextInRange([[bufferPosition.row, 0], bufferPosition])
    prefixRegex = /([\s]*([^\s]*))*$/
    prefixRegex.exec(line)?[2] or ''

  # Order the suggestions based on the prefix
  orderSuggestions: (prefix, suggestions) ->
    # There are more efficient sorting methods but this is simple and the task is quick
    suggestionSwapped = suggestions.length > 1
    upperPrefix = prefix.toUpperCase()
    while suggestionSwapped
      suggestionSwapped = false
      for index in [0...suggestions.length - 1]
        current = suggestions[index].snippet.toUpperCase().indexOf(upperPrefix)
        next = suggestions[index + 1].snippet.toUpperCase().indexOf(upperPrefix)
        if current >= 0 and next >= 0
          if current > next
            suggestionSwapped = true
            temp = suggestions[index]
            suggestions[index] = suggestions[index + 1]
            suggestions[index + 1] = temp
        else if next >= 0
          suggestionSwapped = true
          temp = suggestions[index]
          suggestions[index] = suggestions[index + 1]
          suggestions[index + 1] = temp

  # Fixes the suggestedPrefix.
  # There is an issue with the default function of using the prefix passed into getSuggestions,
  # so you have to define the replacementPrefix for each suggestion.
  setReplacementPrefix: (prefix, suggestions) ->
    for suggestion in suggestions
      suggestion.replacementPrefix = prefix

    return suggestions
